### ISSUE TITLE
Error with some feeds?

### ISSUE THREAD

**Issue by typesoshee** [chase-seibert/rsscombine#1]
With some feeds entered into the rsscombine.yml file, everything seems to work great, but with other feeds, it doesn't seem to work. 

Here's an example of a feed that I find doesn't work:
https://rsshub-nog.herokuapp.com/weibo/user/6372196907

This is the output from the Heroku log when I try to access the RSSCOMBINE_LINK (the RSSCOMBINE_LINK webpage ends up with a Heroku error page):

2021-11-04T23:23:38.790650+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/" host=rsscombine-ng-weibo.herokuapp.com request_id=f72dac7a-6ecb-4cfa-9846-397cd99f3963 fwd="184.153.10.154" dyno=web.1 connect=0ms service=64ms status=503 bytes=0 protocol=https
2021-11-04T23:23:38.728534+00:00 app[web.1]: 2021/11/04 23:23:38 Fetching URL: https://rsshub-nog.herokuapp.com/weibo/user/6372196907
2021-11-04T23:23:38.728750+00:00 app[web.1]: 2021/11/04 23:23:38 Fetching URL: https://rsshub-nog.herokuapp.com/755/user/yamazaki-rena
2021-11-04T23:23:38.789604+00:00 app[web.1]: 2021/11/04 23:23:38 http: panic serving 10.1.61.206:35314: runtime error: slice bounds out of range
2021-11-04T23:23:38.789606+00:00 app[web.1]: goroutine 24 [running]:
2021-11-04T23:23:38.789607+00:00 app[web.1]: net/http.(*conn).serve.func1(0xc4200a4640)
2021-11-04T23:23:38.789608+00:00 app[web.1]: 	/tmp/codon/tmp/cache/go1.10.2/go/src/net/http/server.go:1726 +0xd0
2021-11-04T23:23:38.789608+00:00 app[web.1]: panic(0x8d8b80, 0xce37c0)
2021-11-04T23:23:38.789609+00:00 app[web.1]: 	/tmp/codon/tmp/cache/go1.10.2/go/src/runtime/panic.go:502 +0x229
2021-11-04T23:23:38.789609+00:00 app[web.1]: github.com/rsscombine.combineallFeeds(0xc42046c2b0, 0x2, 0x2, 0xc42046c2b0)
2021-11-04T23:23:38.789610+00:00 app[web.1]: 	/tmp/tmp.0OIDh3HYcf/.go/src/github.com/rsscombine/rsscombine.go:157 +0x8a7
2021-11-04T23:23:38.789610+00:00 app[web.1]: github.com/rsscombine.GetAtomFeed(0xc42002ba00)
2021-11-04T23:23:38.789610+00:00 app[web.1]: 	/tmp/tmp.0OIDh3HYcf/.go/src/github.com/rsscombine/rsscombine.go:182 +0x49
2021-11-04T23:23:38.789611+00:00 app[web.1]: main.handler(0x9cc800, 0xc4203900e0, 0xc42027e000)
2021-11-04T23:23:38.789611+00:00 app[web.1]: 	/tmp/tmp.0OIDh3HYcf/.go/src/github.com/rsscombine/cmd/rsscombine-server/main.go:22 +0x1df
2021-11-04T23:23:38.789612+00:00 app[web.1]: net/http.HandlerFunc.ServeHTTP(0x98a798, 0x9cc800, 0xc4203900e0, 0xc42027e000)
2021-11-04T23:23:38.789612+00:00 app[web.1]: 	/tmp/codon/tmp/cache/go1.10.2/go/src/net/http/server.go:1947 +0x44
2021-11-04T23:23:38.789612+00:00 app[web.1]: net/http.(*ServeMux).ServeHTTP(0xd0db00, 0x9cc800, 0xc4203900e0, 0xc42027e000)
2021-11-04T23:23:38.789613+00:00 app[web.1]: 	/tmp/codon/tmp/cache/go1.10.2/go/src/net/http/server.go:2337 +0x130
2021-11-04T23:23:38.789613+00:00 app[web.1]: net/http.serverHandler.ServeHTTP(0xc42019c8f0, 0x9cc800, 0xc4203900e0, 0xc42027e000)
2021-11-04T23:23:38.789613+00:00 app[web.1]: 	/tmp/codon/tmp/cache/go1.10.2/go/src/net/http/server.go:2694 +0xbc
2021-11-04T23:23:38.789613+00:00 app[web.1]: net/http.(*conn).serve(0xc4200a4640, 0x9ccd80, 0xc4203fa080)
2021-11-04T23:23:38.789614+00:00 app[web.1]: 	/tmp/codon/tmp/cache/go1.10.2/go/src/net/http/server.go:1830 +0x651
2021-11-04T23:23:38.789614+00:00 app[web.1]: created by net/http.(*Server).Serve
2021-11-04T23:23:38.789615+00:00 app[web.1]: 	/tmp/codon/tmp/cache/go1.10.2/go/src/net/http/server.go:2795 +0x27b
2021-11-04T23:23:39.174143+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=rsscombine-ng-weibo.herokuapp.com request_id=2436adfa-45f6-4a1d-ac1b-4a21f12c9a0f fwd="184.153.10.154" dyno=web.1 connect=0ms service=0ms status=200 bytes=94 protocol=https

**Comment by bw4518** [comment]
Yes, doesn't work for me either. Well it does with default sample feeds, but anything more "intensive" results in some type of error. 

This is an error I get when testing with 10 YouTube feeds only.
`http: panic serving 127.0.0.1:42874: runtime error: index out of range [0] with length 0
goroutine 21
`

This is when I mix in some other random feeds.
`
http: panic serving 127.0.0.1:52352: runtime error: invalid memory address or nil pointer dereference
goroutine 8
`


..or when I give it some not very good feeds (like BitChute feeds), 

> Could not determine author for _feedurl_

`
http: panic serving 127.0.0.1:52402: runtime error: slice bounds out of range [:10] with capacity 8
goroutine 5 
`

I don't know if it needs better parser or why it's that "picky" about feeds you use with it.
